export * from './transform-engineering';
export * from './accelerate-time-to-market';
export * from './collaboration-and-transparency';
export * from './reduce-operational-costs';
export * from './leverage-ai';
export * from './simplify-complex-infrastructure';
export * from './enable-self-service';
export * from './gain-competitive-edge';
export * from './into-the-future';
